version: '3.7'

services:
  db:
    image: postgres:12
    container_name: web_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks: 
      - app-networks

  backend:
    image: 'backend:${TAG-latest}'
    container_name: web_api
    depends_on: 
      - db
    env_file: 
      - .env
    build: 
      context: ./app/backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_JUPYTER: ${INSTALL_JUPYTER-true}
    environment:
      - ENV=development
    volumes: 
      - ./app/backend:/app
    ports:
      - 8002:8000
      - 8888:8888
    networks: 
      - app-networks
    
    

volumes:
  postgres_data:

networks:
  app-networks: