version: '3.7'

services:
  web_service:
    build: .
    container_name: api
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8002:8000
    networks: 
      - app-networks

networks:
  app-networks: